# acountry
# Autogenerated from man page /usr/share/man/man1/acountry.1.gz
complete -c acountry -s d -d 'Print some extra debugging output'
complete -c acountry -s h -s '?' -d 'Display this help and exit'
complete -c acountry -s v -d 'Be more verbose.  Print extra information'

