# ahost
# Autogenerated from man page /usr/share/man/man1/ahost.1.gz
complete -c ahost -s d -d 'Print some extra debugging output'
complete -c ahost -s h -s '?' -d 'Display this help and exit'
complete -c ahost -s t -d 'If type is "a", print the A record (default)'
complete -c ahost -s s -d 'Specify the domain to search instead of using the default values from'

