# airdecap-ng
# Autogenerated from man page /usr/share/man/man1/airdecap-ng.1.gz
complete -c airdecap-ng -s H -l help -d 'Shows the help screen'
complete -c airdecap-ng -s l -d 'Do not remove the 802. 11 header'
complete -c airdecap-ng -s b -d 'Access point MAC address filter'
complete -c airdecap-ng -s k -d 'WPA Pairwise Master Key in hex'
complete -c airdecap-ng -s e -d 'Target network SSID.  For SSID containing special characters, see https://www'
complete -c airdecap-ng -s p -d 'Target network WPA passphrase'
complete -c airdecap-ng -s w -d 'Target network WEP key in hex'

