# airdrop-ng
# Autogenerated from man page /usr/share/man/man1/airdrop-ng.1.gz
complete -c airdrop-ng -s d -l driver -d 'Driver for injection.  Supported drivers are: '
complete -c airdrop-ng -s i -l interface -d 'Interface of the card for injection.  IE, -i mon0'
complete -c airdrop-ng -s l -l logging -d 'Enable logging to a file'
complete -c airdrop-ng -s r -l rule -d 'This is what separates airdrop-ng from other deauthentication applications'
complete -c airdrop-ng -s s -l sleep -d 'Time to sleep before sending next set of packets'
complete -c airdrop-ng -s t -l dump -d 'Path to the txt file in . CSV format from airodump-ng'
complete -c airdrop-ng -s u -l update -d 'Updates OUI list and to latest version of airdrop-ng'

