# airdecloak-ng
# Autogenerated from man page /usr/share/man/man1/airdecloak-ng.1.gz
complete -c airdecloak-ng -s h -l help -d 'Shows the help screen'
complete -c airdecloak-ng -s i -d 'Path to the capture file'
complete -c airdecloak-ng -l ssid -d 'Essid of the network (not yet implemented) to filter'
complete -c airdecloak-ng -l bssid -d 'BSSID of the network to filter'
complete -c airdecloak-ng -l null-packets -d 'Assume that null packets can be cloaked'
complete -c airdecloak-ng -l disable-base-filter -d 'Do not apply base filter'
complete -c airdecloak-ng -l drop-frag -d 'Drop fragmented packets'
complete -c airdecloak-ng -l filters -d 'Apply different filters (separated by a comma).  See below'

