# airgraph-ng
# Autogenerated from man page /usr/share/man/man1/airgraph-ng.1.gz
complete -c airgraph-ng -s h -d 'Shows the help screen'
complete -c airgraph-ng -s i -d 'Airodump-ng CSV file'
complete -c airgraph-ng -s o -d 'Output png file'
complete -c airgraph-ng -s g -d 'Choose the Graph Type'
complete -c airgraph-ng -s a -d 'Print the about'

