# airmon-ng
# Autogenerated from man page /usr/share/man/man8/airmon-ng.8.gz
complete -c airmon-ng -l verbose -d 'This flag must precede start/stop/check and can be combined with other parame…'
complete -c airmon-ng -l debug -d 'This flag must precede start/stop/check and can be combined with other parame…'
complete -c airmon-ng -l elite -d 'WARNING: DO NOT USE: This flag must precede start or stop and will prevent ai…'

