# airolib-ng
# Autogenerated from man page /usr/share/man/man1/airolib-ng.1.gz
complete -c airolib-ng -l stats -d 'Output information about the database'
complete -c airolib-ng -l sql -d 'Execute specified SQL statement'
complete -c airolib-ng -l clean -d 'Clean the database from old junk'
complete -c airolib-ng -l batch -d 'Start/Restart batch-processing all combinations of ESSIDs and passwords'
complete -c airolib-ng -l verify -d 'Verify a set of randomly chosen PMKs'
complete -c airolib-ng -l import -d 'Import a flat file as a list of ESSIDs or passwords'
complete -c airolib-ng -l export -d 'Export to a cowpatty file'

