# airodump-join
# Autogenerated from man page /usr/share/man/man1/airodump-join.1.gz
complete -c airodump-join -s i -d 'Input Files [ foo_name_1 foo_name_2 foo_name_3 . ]'
complete -c airodump-join -s o -d 'Output File'

