# airserv-ng
# Autogenerated from man page /usr/share/man/man8/airserv-ng.8.gz
complete -c airserv-ng -s h -d 'Shows the help screen'
complete -c airserv-ng -s p -d 'TCP port to listen on (by default: 666)'
complete -c airserv-ng -s d -d 'Wifi interface to use'
complete -c airserv-ng -s c -d 'Lock interface to this channel'
complete -c airserv-ng -s v -d 'Debug level.  There are 3 debug levels'

