# airtun-ng
# Autogenerated from man page /usr/share/man/man8/airtun-ng.8.gz
complete -c airtun-ng -s H -l help -d 'Shows the help screen'
complete -c airtun-ng -s x -d 'Sets maximum number of packets per second'
complete -c airtun-ng -s a -d 'Specifies the BSSID for the iee802. 11 header'
complete -c airtun-ng -s h -d 'Specifies the source MAC for the iee802. 11 header'
complete -c airtun-ng -s i -d 'Sets the capture interface'
complete -c airtun-ng -s r -d 'Specifies a file to read 802. 11 frames'
complete -c airtun-ng -s y -d 'Is the name of the file, which provides the keystream for WEP encoding'
complete -c airtun-ng -s w -d 'This is the WEP key to en-/decrypt all traffic going through the tunnel'
complete -c airtun-ng -s e -d 'Sets the target network SSID (use with -p)'
complete -c airtun-ng -s p -d 'Use this WPA passphrase to decrypt packets (use with -a and -e)'
complete -c airtun-ng -s t -d 'Defines the ToDS and FromDS bit in the ieee802. 11 header'
complete -c airtun-ng -s m -l netmask -d 'Filters networks based on bssid ^ netmask combination'
complete -c airtun-ng -s d -l bssid -d 'Filters networks based on the <BSSID>.  Used in replay mode'
complete -c airtun-ng -s f -l repeat -d 'Enables replay mode'
complete -c airtun-ng -s s -d 'Set Transmitter MAC address for WDS Mode'
complete -c airtun-ng -s b -d 'Bidirectional mode'

