# airventriloquist-ng
# Autogenerated from man page /usr/share/man/man8/airventriloquist-ng.8.gz
complete -c airventriloquist-ng -l help -d 'Shows the help screen'
complete -c airventriloquist-ng -s i -d 'Interface to capture and inject.  Mandatory option'
complete -c airventriloquist-ng -s d -l deauth -d 'Sends active deauthentications frames to encrypted stations'
complete -c airventriloquist-ng -s e -l essid -d 'ESSID of target network'
complete -c airventriloquist-ng -s p -l passphrase -d 'WPA Passphrase of the target network'
complete -c airventriloquist-ng -s c -l icmp -d 'Respond to all ICMP frames (Debug)'
complete -c airventriloquist-ng -s n -l dns -d 'IP to resolve all DNS queries to'
complete -c airventriloquist-ng -s s -l hijack -d 'URL to look for in HTTP requests when hijacking connections'
complete -c airventriloquist-ng -s r -l redirect -d 'URL to redirect hijacked connections to'
complete -c airventriloquist-ng -s v -l verbose -d 'Verbose output'

