# besside-ng
# Autogenerated from man page /usr/share/man/man8/besside-ng.8.gz
complete -c besside-ng -s b -d 'Specifies the target\'s BSSID'
complete -c besside-ng -s s -d 'Where to upload capture file for cracking.  A good choice is wpa. darkircop'
complete -c besside-ng -s c -d 'Channel lock'
complete -c besside-ng -s p -d 'Packages per second to send (flood rate)'
complete -c besside-ng -s W -d 'Crack only WPA networks'
complete -c besside-ng -s v -d 'Verbose mode.  Use -vv for more verbose, -vv for even more and so on'
complete -c besside-ng -s h -d 'Help screen'

