# bundle-gem
# Autogenerated from man page /usr/share/man/man1/bundle-gem.1.gz
complete -c bundle-gem -l exe -s b -l bin
complete -c bundle-gem -l no-exe
complete -c bundle-gem -l coc
complete -c bundle-gem -l no-coc
complete -c bundle-gem -l ext -l ext
complete -c bundle-gem -l no-ext
complete -c bundle-gem -l mit
complete -c bundle-gem -l no-mit
complete -c bundle-gem -s t -l test -l test -l test
complete -c bundle-gem -l ci -l ci -l ci -l ci
complete -c bundle-gem -l linter -l linter -l linter
complete -c bundle-gem -s e -l edit

