# bundle-exec
# Autogenerated from man page /usr/share/man/man1/bundle-exec.1.gz
complete -c bundle-exec -l keep-file-descriptors -d 'Exec in Ruby 2. 0 began discarding non-standard file descriptors'

