# check-regexp
# Autogenerated from man page /usr/share/man/man1/check-regexp.1.gz
complete -c check-regexp -s h -l help -d 'Print help and exit'
complete -c check-regexp -s V -l version -d 'Print version and exit AUTHOR check-regexp was written by Lorenzo Bettini <www'

