# clusterdb
# Autogenerated from man page /usr/share/man/man1/clusterdb.1.gz
complete -c clusterdb -o 'a
.br
--all' -d 'Cluster all databases'
complete -c clusterdb -o 'e
.br
--echo' -d 'Echo the commands that clusterdb generates and sends to the server'
complete -c clusterdb -o 'q
.br
--quiet' -d 'Do not display progress messages'
complete -c clusterdb -s t -d 'Cluster table only'
complete -c clusterdb -o 'v
.br
--verbose' -d 'Print detailed information during processing'
complete -c clusterdb -o 'V
.br
--version' -d 'Print the clusterdb version and exit'
complete -c clusterdb -o '?
.br
--help' -d 'Show help about clusterdb command line arguments, and exit'
complete -c clusterdb -s h -d 'Specifies the host name of the machine on which the server is running'
complete -c clusterdb -s p -d 'Specifies the TCP port or local Unix domain socket file extension on which th…'
complete -c clusterdb -s U -d 'User name to connect as'
complete -c clusterdb -o 'w
.br
--no-password' -d 'Never issue a password prompt'
complete -c clusterdb -o 'W
.br
--password' -d 'Force clusterdb to prompt for a password before connecting to a database'
complete -c clusterdb -l maintenance-db -d 'Specifies the name of the database to connect to to discover which databases …'
complete -c clusterdb -s a
complete -c clusterdb -l all
complete -c clusterdb -o a/--all -d 'is not used'
complete -c clusterdb -s e
complete -c clusterdb -l echo
complete -c clusterdb -s q
complete -c clusterdb -l quiet
complete -c clusterdb -l table
complete -c clusterdb -s v
complete -c clusterdb -l verbose
complete -c clusterdb -s V
complete -c clusterdb -l version
complete -c clusterdb -s '?'
complete -c clusterdb -l help
complete -c clusterdb -l host
complete -c clusterdb -l port
complete -c clusterdb -l username
complete -c clusterdb -s w
complete -c clusterdb -l no-password
complete -c clusterdb -s W
complete -c clusterdb -l password

