# createdb
# Autogenerated from man page /usr/share/man/man1/createdb.1.gz
complete -c createdb -s D -d 'Specifies the default tablespace for the database'
complete -c createdb -o 'e
.br
--echo' -d 'Echo the commands that createdb generates and sends to the server'
complete -c createdb -s E -d 'Specifies the character encoding scheme to be used in this database'
complete -c createdb -s l -d 'Specifies the locale to be used in this database'
complete -c createdb -l lc-collate -d 'Specifies the LC_COLLATE setting to be used in this database'
complete -c createdb -l lc-ctype -d 'Specifies the LC_CTYPE setting to be used in this database'
complete -c createdb -l icu-locale -d 'Specifies the ICU locale ID to be used in this database, if the ICU locale pr…'
complete -c createdb -l locale-provider -d 'Specifies the locale provider for the database\\*(Aqs default collation'
complete -c createdb -s O -d 'Specifies the database user who will own the new database'
complete -c createdb -s S -d 'Specifies the database creation strategy'
complete -c createdb -s T -d 'Specifies the template database from which to build this database'
complete -c createdb -o 'V
.br
--version' -d 'Print the createdb version and exit'
complete -c createdb -o '?
.br
--help' -d 'Show help about createdb command line arguments, and exit'
complete -c createdb -s h -d 'Specifies the host name of the machine on which the server is running'
complete -c createdb -s p -d 'Specifies the TCP port or the local Unix domain socket file extension on whic…'
complete -c createdb -s U -d 'User name to connect as'
complete -c createdb -o 'w
.br
--no-password' -d 'Never issue a password prompt'
complete -c createdb -o 'W
.br
--password' -d 'Force createdb to prompt for a password before connecting to a database'
complete -c createdb -l maintenance-db -d 'Specifies the name of the database to connect to when creating the new databa…'
complete -c createdb -l tablespace
complete -c createdb -s e
complete -c createdb -l echo
complete -c createdb -l encoding
complete -c createdb -l locale
complete -c createdb -l owner
complete -c createdb -l strategy
complete -c createdb -l template
complete -c createdb -s V
complete -c createdb -l version
complete -c createdb -s '?'
complete -c createdb -l help
complete -c createdb -l host
complete -c createdb -l port
complete -c createdb -l username
complete -c createdb -s w
complete -c createdb -l no-password
complete -c createdb -s W
complete -c createdb -l password

