# debuginfod-find
# Autogenerated from man page /usr/share/man/man1/debuginfod-find.1.gz
complete -c debuginfod-find -s v -d 'Increase verbosity, including printing frequent download-progress messages an…'

