# dropuser
# Autogenerated from man page /usr/share/man/man1/dropuser.1.gz
complete -c dropuser -o 'e
.br
--echo' -d 'Echo the commands that dropuser generates and sends to the server'
complete -c dropuser -o 'i
.br
--interactive' -d 'Prompt for confirmation before actually removing the user, and prompt for the…'
complete -c dropuser -o 'V
.br
--version' -d 'Print the dropuser version and exit'
complete -c dropuser -l if-exists -d 'Do not throw an error if the user does not exist'
complete -c dropuser -o '?
.br
--help' -d 'Show help about dropuser command line arguments, and exit'
complete -c dropuser -s h -d 'Specifies the host name of the machine on which the server is running'
complete -c dropuser -s p -d 'Specifies the TCP port or local Unix domain socket file extension on which th…'
complete -c dropuser -s U -d 'User name to connect as (not the user name to drop)'
complete -c dropuser -o 'w
.br
--no-password' -d 'Never issue a password prompt'
complete -c dropuser -o 'W
.br
--password' -d 'Force dropuser to prompt for a password before connecting to a database'
complete -c dropuser -o i/--interactive -d 'option is used'
complete -c dropuser -s e
complete -c dropuser -l echo
complete -c dropuser -s i
complete -c dropuser -l interactive
complete -c dropuser -s V
complete -c dropuser -l version
complete -c dropuser -s '?'
complete -c dropuser -l help
complete -c dropuser -l host
complete -c dropuser -l port
complete -c dropuser -l username
complete -c dropuser -s w
complete -c dropuser -l no-password
complete -c dropuser -s W
complete -c dropuser -l password

