# dropdb
# Autogenerated from man page /usr/share/man/man1/dropdb.1.gz
complete -c dropdb -o 'e
.br
--echo' -d 'Echo the commands that dropdb generates and sends to the server'
complete -c dropdb -o 'f
.br
--force' -d 'Attempt to terminate all existing connections to the target database before d…'
complete -c dropdb -o 'i
.br
--interactive' -d 'Issues a verification prompt before doing anything destructive'
complete -c dropdb -o 'V
.br
--version' -d 'Print the dropdb version and exit'
complete -c dropdb -l if-exists -d 'Do not throw an error if the database does not exist'
complete -c dropdb -o '?
.br
--help' -d 'Show help about dropdb command line arguments, and exit'
complete -c dropdb -s h -d 'Specifies the host name of the machine on which the server is running'
complete -c dropdb -s p -d 'Specifies the TCP port or local Unix domain socket file extension on which th…'
complete -c dropdb -s U -d 'User name to connect as'
complete -c dropdb -o 'w
.br
--no-password' -d 'Never issue a password prompt'
complete -c dropdb -o 'W
.br
--password' -d 'Force dropdb to prompt for a password before connecting to a database'
complete -c dropdb -l maintenance-db -d 'Specifies the name of the database to connect to in order to drop the target …'
complete -c dropdb -s e
complete -c dropdb -l echo
complete -c dropdb -s f
complete -c dropdb -l force
complete -c dropdb -s i
complete -c dropdb -l interactive
complete -c dropdb -s V
complete -c dropdb -l version
complete -c dropdb -s '?'
complete -c dropdb -l help
complete -c dropdb -l host
complete -c dropdb -l port
complete -c dropdb -l username
complete -c dropdb -s w
complete -c dropdb -l no-password
complete -c dropdb -s W
complete -c dropdb -l password

