# easside-ng
# Autogenerated from man page /usr/share/man/man8/easside-ng.8.gz
complete -c easside-ng -s h -d 'Shows the help screen'
complete -c easside-ng -s v -d 'Victim BSSID (Optional)'
complete -c easside-ng -s m -d 'Source MAC address to be used (Optional)'
complete -c easside-ng -s i -d 'Source IP address to be used on the wireless LAN'
complete -c easside-ng -s r -d 'IP address of the AP router'
complete -c easside-ng -s s -d 'IP address of Buddy-ng server (Mandatory)'
complete -c easside-ng -s f -d 'Wireless interface to use (Mandatory)'
complete -c easside-ng -s c -d 'Lock interface to this channel (Optional)'
complete -c easside-ng -s n -d 'Determine Internet IP only'

