# ffmpeg-formats
# Autogenerated from man page /usr/share/man/man1/ffmpeg-formats.1.gz
complete -c ffmpeg-formats -o ignore_loop
complete -c ffmpeg-formats -o max_fps
complete -c ffmpeg-formats -o default_fps
complete -c ffmpeg-formats -o no_resync_search
complete -c ffmpeg-formats -o flv_metadata
complete -c ffmpeg-formats -o flv_ignore_prevtag
complete -c ffmpeg-formats -o flv_full_metadata
complete -c ffmpeg-formats -o hls_enc
complete -c ffmpeg-formats -o hls_enc_key
complete -c ffmpeg-formats -o hls_enc_key_url
complete -c ffmpeg-formats -o hls_enc_iv
complete -c ffmpeg-formats -o ignore_io_errors
complete -c ffmpeg-formats -o moov_size
complete -c ffmpeg-formats -o movflags
complete -c ffmpeg-formats -o frag_duration
complete -c ffmpeg-formats -o frag_size
complete -c ffmpeg-formats -o min_frag_duration
complete -c ffmpeg-formats -o write_tmcd
complete -c ffmpeg-formats -o write_btrt
complete -c ffmpeg-formats -o write_prft
complete -c ffmpeg-formats -o empty_hdlr_name
complete -c ffmpeg-formats -o movie_timescale
complete -c ffmpeg-formats -o video_track_timescale
complete -c ffmpeg-formats -s 1 -d '20 ms is used for CBR streams, the highest multiple of the frame duration whi…'
complete -c ffmpeg-formats -o syncpoints
complete -c ffmpeg-formats -o write_index
complete -c ffmpeg-formats -o page_duration
complete -c ffmpeg-formats -o serial_offset

