# gnome-extensions
# Autogenerated from man page /usr/share/man/man1/gnome-extensions.1.gz
complete -c gnome-extensions -l quiet -s q
complete -c gnome-extensions -l user
complete -c gnome-extensions -l system
complete -c gnome-extensions -l enabled
complete -c gnome-extensions -l disabled
complete -c gnome-extensions -l prefs
complete -c gnome-extensions -l updates
complete -c gnome-extensions -s d -l details
complete -c gnome-extensions -l name
complete -c gnome-extensions -l description
complete -c gnome-extensions -l uuid
complete -c gnome-extensions -l template
complete -c gnome-extensions -s i -l interactive
complete -c gnome-extensions -l extra-source
complete -c gnome-extensions -l schema
complete -c gnome-extensions -l podir -d 'option can be used to point to the correct directory'
complete -c gnome-extensions -l gettext-domain
complete -c gnome-extensions -s f -l force
complete -c gnome-extensions -s o -l out-dir

