# gnome-firmware
# Autogenerated from man page /usr/share/man/man1/gnome-firmware.1.gz
complete -c gnome-firmware -s h -l help -d 'Show help options . SS "Application Options:"'
complete -c gnome-firmware -s v -l verbose -d 'Show extra debugging information'

