# gnome-shell
# Autogenerated from man page /usr/share/man/man1/gnome-shell.1.gz
complete -c gnome-shell -l wayland -d 'Run as a wayland compositor'
complete -c gnome-shell -l display-server -d 'Run as a full display server, rather than nested'
complete -c gnome-shell -l nested -d 'Run as a nested compositor'
complete -c gnome-shell -l no-x11 -d 'Run wayland compositor without starting Xwayland'
complete -c gnome-shell -l x11 -d 'Run with X11 backend'
complete -c gnome-shell -l wayland-display -d 'Wayland display name to use'
complete -c gnome-shell -s d -l display -d 'X display to use'
complete -c gnome-shell -s r -l replace -d 'Replace the running window manager'
complete -c gnome-shell -l sm-disable -d 'Disable connection to the session manager'
complete -c gnome-shell -l sm-client-id -d 'Specify session management ID'
complete -c gnome-shell -l sm-save-file -d 'Initialize session from FILE'
complete -c gnome-shell -l sync -d 'Make X calls synchronous'
complete -c gnome-shell -l mode -d 'Use a specific mode, e. g.  "gdm" for login screen'
complete -c gnome-shell -l list-modes -d 'List possible modes and exit'
complete -c gnome-shell -l version -d 'Print version and exit'
complete -c gnome-shell -l help -d 'Display help and exit'

