# hostapd
# Autogenerated from man page /usr/share/man/man8/hostapd.8.gz
complete -c hostapd -s h -d 'Show usage'
complete -c hostapd -s d -d 'Show more debug messages'
complete -c hostapd -o dd -d 'Show even more debug messages'
complete -c hostapd -s B -d 'Run daemon in the background'
complete -c hostapd -s P -d 'Path to PID file'
complete -c hostapd -s K -d 'Include key data in debug messages'
complete -c hostapd -s t -d 'Include timestamps in some debug messages'
complete -c hostapd -s v -d 'Show hostapd version.  SEE ALSO hostapd_cli (1)'

