# i3-dmenu-desktop
# Autogenerated from man page /usr/share/man/man1/i3-dmenu-desktop.1.gz
complete -c i3-dmenu-desktop -l dmenu -d 'Execute command instead of \'dmenu -i\''
complete -c i3-dmenu-desktop -l entry-type -d 'Display the (localized) \\*(L"Name\\*(R" (type = name), the command (type = com…'

