# jar-openjdk17
# Autogenerated from man page /usr/share/man/man1/jar-openjdk17.1.gz
complete -c jar-openjdk17 -l module-version -d '[bu] 2'
complete -c jar-openjdk17 -l hash-modules -d '[bu] 2'
complete -c jar-openjdk17 -l module-path
complete -c jar-openjdk17 -s c -l create -d 'Creates the archive'
complete -c jar-openjdk17 -s i -l generate-index -d 'Generates index information for the specified JAR file'
complete -c jar-openjdk17 -s t -l list -d 'Lists the table of contents for the archive'
complete -c jar-openjdk17 -s u -l update -d 'Updates an existing JAR file'
complete -c jar-openjdk17 -s x -l extract -d 'Extracts the named (or all) files from the archive'
complete -c jar-openjdk17 -s d -l describe-module -d 'Prints the module descriptor or automatic module name'
complete -c jar-openjdk17 -s C -d 'Changes the specified directory and includes the files specified at the end o…'
complete -c jar-openjdk17 -s f -l file -d 'Specifies the archive file name'
complete -c jar-openjdk17 -l release -d 'Creates a multirelease JAR file'
complete -c jar-openjdk17 -s v -l verbose -d 'Sends or prints verbose output to standard output'
complete -c jar-openjdk17 -s e -l main-class -d 'Specifies the application entry point for standalone applications bundled int…'
complete -c jar-openjdk17 -s m -l manifest -d 'Includes the manifest information from the given manifest file'
complete -c jar-openjdk17 -s M -l no-manifest -d 'Doesn[aq]t create a manifest file for the entries'
complete -c jar-openjdk17 -s p -d 'Specifies the location of module dependence for generating the hash'
complete -c jar-openjdk17 -s 0 -l no-compress -d 'Stores without using ZIP compression.  OTHER OPTIONS'
complete -c jar-openjdk17 -s h -l help -d 'Displays the command-line help for the jar command or optionally the compatib…'
complete -c jar-openjdk17 -l help-extra -d 'Displays help on extra options'
complete -c jar-openjdk17 -l version -d 'Prints the program version'

