# jcmd-openjdk17
# Autogenerated from man page /usr/share/man/man1/jcmd-openjdk17.1.gz
complete -c jcmd-openjdk17 -o all -d 'Compiler. codecache Prints code cache layout and bounds.  Impact: Low'
complete -c jcmd-openjdk17 -s l -d '(BOOLEAN, false) VM'
complete -c jcmd-openjdk17 -s i -d '(BOOLEAN, false) [bu] 2'
complete -c jcmd-openjdk17 -s s -d subclasses
complete -c jcmd-openjdk17 -o verbose -d 'table (BOOLEAN, false) VM. symboltable [options] Dumps the symbol table'
complete -c jcmd-openjdk17 -o date -d '(BOOLEAN, false) VM. version Prints JVM version information.  Impact: Low'

