# jfr-openjdk17
# Autogenerated from man page /usr/share/man/man1/jfr-openjdk17.1.gz
complete -c jfr-openjdk17 -l xml -d 'Print the recording in XML format'
complete -c jfr-openjdk17 -l json -d 'Print the recording in JSON format'
complete -c jfr-openjdk17 -l categories -d 'Select events matching a category name'
complete -c jfr-openjdk17 -l events -d 'Select events matching an event name'
complete -c jfr-openjdk17 -l stack-depth -d 'Number of frames in stack traces, by default 5 <file> Location of the recordi…'
complete -c jfr-openjdk17 -l output -d 'The location to write the disassembled file, by default the current directory'
complete -c jfr-openjdk17 -l max-chunks -d 'Maximum number of chunks per file, by default 5'
complete -c jfr-openjdk17 -l max-size -d 'Maximum number of bytes per file'

