# jps-openjdk17
# Autogenerated from man page /usr/share/man/man1/jps-openjdk17.1.gz
complete -c jps-openjdk17 -s q -d 'Suppresses the output of the class name, JAR file name, and arguments passed …'
complete -c jps-openjdk17 -o mlvV -d 'You can specify any combination of these options'
complete -c jps-openjdk17 -s m -d 'The output may be null for embedded JVMs.  [bu] 2'
complete -c jps-openjdk17 -s l -d 'main class or the full path name to the application[aq]s JAR file.  [bu] 2'
complete -c jps-openjdk17 -s v -d '[bu] 2'
complete -c jps-openjdk17 -s V -d 'arguments passed to the main method, producing a list of only local JVM ident…'
complete -c jps-openjdk17 -o help -d 'Displays the help message for the jps command.  DESCRIPTION'

