# jrunscript-openjdk20
# Autogenerated from man page /usr/share/man/man1/jrunscript-openjdk20.1.gz
complete -c jrunscript-openjdk20 -o '\\f' -d 'Enters interactive mode to read and evaluate a script from standard input'
complete -c jrunscript-openjdk20 -o cp -o classpath -d 'Indicates where any class files are that the script needs to access'
complete -c jrunscript-openjdk20 -o Dname -d 'Sets a Java system property'
complete -c jrunscript-openjdk20 -o Jflag -d 'Passes flag directly to the Java Virtual Machine where the jrunscript command…'
complete -c jrunscript-openjdk20 -s l -d 'Uses the specified scripting language.  By default, JavaScript is used'
complete -c jrunscript-openjdk20 -s e -d 'Evaluates the specified script'
complete -c jrunscript-openjdk20 -o encoding -d 'Specifies the character encoding used to read script files'
complete -c jrunscript-openjdk20 -s f -d 'Evaluates the specified script file (batch mode)'
complete -c jrunscript-openjdk20 -o help -s '?' -d 'Displays a help message and exits'
complete -c jrunscript-openjdk20 -s q -d 'Lists all script engines available and exits.  ARGUMENTS'

