# jstack-openjdk17
# Autogenerated from man page /usr/share/man/man1/jstack-openjdk17.1.gz
complete -c jstack-openjdk17 -s l -d 'The long listing option prints additional information about locks'
complete -c jstack-openjdk17 -s h -o help -d 'Prints a help message'

