# makeivs-ng
# Autogenerated from man page /usr/share/man/man1/makeivs-ng.1.gz
complete -c makeivs-ng -s b -l bssid -d 'Set the BSSID (Access Point MAC)'
complete -c makeivs-ng -s f -l first -d 'Value for the first IV generated'
complete -c makeivs-ng -s k -l key -d 'Target network WEP key in hex'
complete -c makeivs-ng -s s -l seed -d 'Seed used to setup random generator'
complete -c makeivs-ng -s w -l write -d 'Filename to write IVs into'
complete -c makeivs-ng -s c -l count -d 'Amount of IVs to generate.  Default value is 100000'
complete -c makeivs-ng -s d -l dupe -d 'Percentage of duplicate IVs'
complete -c makeivs-ng -s e -l error -d 'Percentage of erroneous keystreams'
complete -c makeivs-ng -s l -l length -d 'Size of keystreams.  Default: 16 bytes'
complete -c makeivs-ng -s n -l nofms -d 'Ignores weak IVs'
complete -c makeivs-ng -s p -l prng -d 'Use random values when generating IVs.  Default is to use sequential values'
complete -c makeivs-ng -l help -d 'Show help screen.  EXAMPLE makeivs makeivs -w out'

