# pg_config
# Autogenerated from man page /usr/share/man/man1/pg_config.1.gz
complete -c pg_config -l bindir -d 'Print the location of user executables'
complete -c pg_config -l docdir -d 'Print the location of documentation files'
complete -c pg_config -l htmldir -d 'Print the location of HTML documentation files'
complete -c pg_config -l includedir -d 'Print the location of C header files of the client interfaces'
complete -c pg_config -l pkgincludedir -d 'Print the location of other C header files'
complete -c pg_config -l includedir-server -d 'Print the location of C header files for server programming'
complete -c pg_config -l libdir -d 'Print the location of object code libraries'
complete -c pg_config -l pkglibdir -d 'Print the location of dynamically loadable modules, or where the server would…'
complete -c pg_config -l localedir -d 'Print the location of locale support files'
complete -c pg_config -l mandir -d 'Print the location of manual pages'
complete -c pg_config -l sharedir -d 'Print the location of architecture-independent support files'
complete -c pg_config -l sysconfdir -d 'Print the location of system-wide configuration files'
complete -c pg_config -l pgxs -d 'Print the location of extension makefiles'
complete -c pg_config -l configure -d 'Print the options that were given to the configure script when PostgreSQL was…'
complete -c pg_config -l cc -d 'Print the value of the CC variable that was used for building PostgreSQL'
complete -c pg_config -l cppflags -d 'Print the value of the CPPFLAGS variable that was used for building PostgreSQL'
complete -c pg_config -l cflags -d 'Print the value of the CFLAGS variable that was used for building PostgreSQL'
complete -c pg_config -l cflags_sl -d 'Print the value of the CFLAGS_SL variable that was used for building PostgreS…'
complete -c pg_config -l ldflags -d 'Print the value of the LDFLAGS variable that was used for building PostgreSQL'
complete -c pg_config -l ldflags_ex -d 'Print the value of the LDFLAGS_EX variable that was used for building Postgre…'
complete -c pg_config -l ldflags_sl -d 'Print the value of the LDFLAGS_SL variable that was used for building Postgre…'
complete -c pg_config -l libs -d 'Print the value of the LIBS variable that was used for building PostgreSQL'
complete -c pg_config -l version -d 'Print the version of PostgreSQL'
complete -c pg_config -o '?
.br
--help' -d 'Show help about pg_config command line arguments, and exit'
complete -c pg_config -s I -d 'switches)'
complete -c pg_config -s l -d 'switches for external libraries linked into PostgreSQL'
complete -c pg_config -s '?'
complete -c pg_config -l help

