# phar
# Autogenerated from man page /usr/share/man/man1/phar.1.gz
complete -c phar -s f -d 'Specifies the phar file to work on'
complete -c phar -s a -d 'Provide an alias name for the phar file'
complete -c phar -s c -d 'Compression algorithm (see'
complete -c phar -s i -d 'Specifies a regular expression for input files'
complete -c phar -s l -d 'Number of preceding subdirectories to strip from file entries'
complete -c phar -s x -d 'Regular expression for input files to exclude'
complete -c phar -s e -d 'Name of entry to work on (must include PHAR internal directory name if any)'
complete -c phar -s k -d 'Subscription index to work on'
complete -c phar -s m -d 'Meta data to store with entry (serialized php data)'
complete -c phar -s b -d 'Hash-bang line to start the archive (e. g.  #!/usr/bin/php)'
complete -c phar -s h -d 'Selects the hash algorithm (see'
complete -c phar -s p -d 'Location of PHP_Archive class file (pear list-files PHP_Archive)'
complete -c phar -s s -d 'Select the stub file'
complete -c phar -s y -d 'Private key for OpenSSL signing'

