# php-config
# Autogenerated from man page /usr/share/man/man1/php-config.1.gz
complete -c php-config -l prefix -d 'Directory prefix where PHP is installed, e. g.  /usr/local'
complete -c php-config -l includes -d 'List of -I options with all include files'
complete -c php-config -l ldflags -d 'LD Flags which PHP was compiled with'
complete -c php-config -l libs -d 'Extra libraries which PHP was compiled with'
complete -c php-config -l man-dir -d 'The directory prefix where the manpages is installed'
complete -c php-config -l extension-dir -d 'Directory where extensions are searched by default'
complete -c php-config -l include-dir -d 'Directory prefix where header files are installed by default'
complete -c php-config -l php-binary -d 'Full path to php CLI or CGI binary'
complete -c php-config -l php-sapis -d 'Show all SAPI modules available'
complete -c php-config -l configure-options -d 'Configure options to recreate configuration of current PHP installation'
complete -c php-config -l version -d 'PHP version'
complete -c php-config -l vernum -d 'PHP version as integer SEE ALSO php (1) VERSION INFORMATION This manpage desc…'

