# php
# Autogenerated from man page /usr/share/man/man1/php.1.gz
complete -c php -s a -d 'Run PHP interactively'
complete -c php -s b -d 'Bind Path for external FASTCGI Server mode (CGI only)'
complete -c php -s C -d 'Do not chdir to the script\'s directory (CGI only)'
complete -c php -s q -d 'Quiet-mode.  Suppress HTTP header output (CGI only)'
complete -c php -s T -d 'Measure execution time of script repeated count times (CGI only)'
complete -c php -s c -d 'Look for  php. ini file in the directory R path or use the specified R file'
complete -c php -s n -d 'No  php. ini file will be used'
complete -c php -s d -d 'Define INI entry R foo with value R bar'
complete -c php -s e -d 'Generate extended information for debugger/profiler'
complete -c php -s f -d 'Parse and execute R file'
complete -c php -s h -d 'This help'
complete -c php -s H -d 'Hide script name (file) and parameters (args. ) from external tools'
complete -c php -s i -d 'PHP information and configuration'
complete -c php -s l -d 'Syntax check only (lint)'
complete -c php -s m -d 'Show compiled in modules'
complete -c php -s r -d 'Run PHP R code without using script tags  \'<?. ?>\''
complete -c php -s B -d 'Run PHP R begin_code before processing input lines'
complete -c php -s R -d 'Run PHP R code for every input line'
complete -c php -s F -d 'Parse and execute R file for every input line'
complete -c php -s E -d 'Run PHP R end_code after processing all input lines'
complete -c php -s s -d 'Output HTML syntax highlighted source'
complete -c php -s S -d 'Start built-in web server on the given local address and port'
complete -c php -s t -d 'Specify the document root to be used by the built-in web server'
complete -c php -s v -d 'Version number'
complete -c php -s w -d 'Output source with stripped comments and whitespace'
complete -c php -s z -d 'Load Zend extension R file'
complete -c php -l rfunction -d 'R name'
complete -c php -l rf -d 'R name Shows information about function  name'
complete -c php -l rclass -d 'R name'
complete -c php -l rc -d 'R name Shows information about class  name'
complete -c php -l rextension -d 'R name'
complete -c php -l re -d 'R name Shows information about extension  name'
complete -c php -l rzendextension -d 'R name'
complete -c php -l rz -d 'R name Shows information about Zend extension  name'
complete -c php -l rextinfo -d 'R name'
complete -c php -l ri -d 'R name Shows configuration for extension  name'
complete -c php -l interactive
complete -c php -l bindpath
complete -c php -l no-chdir
complete -c php -l no-header
complete -c php -l timing
complete -c php -l php-ini
complete -c php -l no-php-ini
complete -c php -l define
complete -c php -l file
complete -c php -l help
complete -c php -l hide-args
complete -c php -l info
complete -c php -l syntax-check
complete -c php -l modules
complete -c php -l run
complete -c php -l process-begin
complete -c php -l process-code
complete -c php -l process-file
complete -c php -l process-end
complete -c php -l syntax-highlight
complete -c php -l server
complete -c php -l docroot
complete -c php -l version
complete -c php -l strip
complete -c php -l zend-extension
complete -c php -l ini -d 'Show configuration file names FILES'

