# pip-uninstall
# Autogenerated from man page /usr/share/man/man1/pip-uninstall.1.gz
complete -c pip-uninstall -s r -l requirement -d 'Uninstall all the packages listed in the given requirements file'
complete -c pip-uninstall -s y -l yes -d 'Don\\(aqt ask for confirmation of uninstall deletions'
complete -c pip-uninstall -l root-user-action -d 'Action if pip is run as a root user.  By default, a warning message is shown'
complete -c pip-uninstall -l break-system-packages -d 'Allow pip to modify an EXTERNALLY-MANAGED Python installation'

