# polybar-msg
# Autogenerated from man page /usr/share/man/man1/polybar-msg.1.gz
complete -c polybar-msg -s h -l help -d 'Display help text and exit'
complete -c polybar-msg -s p -d 'Send message only to polybar process running under the given process ID'

