# r2agent
# Autogenerated from man page /usr/share/man/man1/r2agent.1.gz
complete -c r2agent -s a -d 'Listen for everyone (localhost by default)'
complete -c r2agent -s d -d 'Run in daemon mode'
complete -c r2agent -s h -d 'Show help prompt'
complete -c r2agent -s s -d 'Run in sandbox mode'
complete -c r2agent -s u -d 'Enable HTTP Authentication support'
complete -c r2agent -s t -d 'user:password authentication file'
complete -c r2agent -s p -d 'Specify listening port for the agent'
complete -c r2agent -s v -d 'Show version information El EXAMPLES Pp TODO SEE ALSO Pp radare2(1)'

