# rasign2
# Autogenerated from man page /usr/share/man/man1/rasign2.1.gz
complete -c rasign2 -s a -d 'Analyze binary after loading it with RCore and use -AA to run aaaa instead of…'
complete -c rasign2 -s A -d 'Treat the provided input file as an ar archive of '
complete -c rasign2 -s c -d 'After finding all signatures, find all signature collisions'
complete -c rasign2 -s f -d 'Interpret the input file as a flirt database and dump the signatures'
complete -c rasign2 -s h -d 'Show usage help message'
complete -c rasign2 -s j -d 'Show output in JSON'
complete -c rasign2 -s o -d 'Add signatures to file, create if it does not exist'
complete -c rasign2 -s q -d 'Enable quiet mode'
complete -c rasign2 -s r -d 'Show output in radare commands'
complete -c rasign2 -s s -d 'Add signatures save all signatures under this signspace'
complete -c rasign2 -s v -d 'Show version information'

