# ravc2
# Autogenerated from man page /usr/share/man/man1/ravc2.1.gz
complete -c ravc2 -s h -d 'Show usage help message'
complete -c ravc2 -s v -d 'Display version El USAGE Available variable types are: Pp ravc2 init echo hel…'

