# rcp
# Autogenerated from man page /usr/share/man/man1/rcp.1.gz
complete -c rcp -s 4 -l ipv4 -d 'use only IPv4'
complete -c rcp -s 6 -l ipv6 -d 'use only IPv6'
complete -c rcp -s d -l target-directory -d 'copy all SOURCE arguments into DIRECTORY'
complete -c rcp -s f -l from -d 'copying from remote host (server use only)'
complete -c rcp -s p -l preserve -d 'attempt to preserve (duplicate) in its copies the modification times and mode…'
complete -c rcp -s r -l recursive -d 'if any of the source files are directories, copies each subtree rooted at tha…'
complete -c rcp -s t -l to -d 'copying to remote host (server use only)'
complete -c rcp -s '?' -l help -d 'give this help list'
complete -c rcp -l usage -d 'give a short usage message'
complete -c rcp -s V -l version -d 'print program version'

