# reindexdb
# Autogenerated from man page /usr/share/man/man1/reindexdb.1.gz
complete -c reindexdb -o 'a
.br
--all' -d 'Reindex all databases'
complete -c reindexdb -l concurrently -d 'Use the CONCURRENTLY option'
complete -c reindexdb -o 'e
.br
--echo' -d 'Echo the commands that reindexdb generates and sends to the server'
complete -c reindexdb -s i -d 'Recreate index only'
complete -c reindexdb -s j -d 'Execute the reindex commands in parallel by running njobs commands simultaneo…'
complete -c reindexdb -o 'q
.br
--quiet' -d 'Do not display progress messages'
complete -c reindexdb -o 's
.br
--system' -d 'Reindex database\\*(Aqs system catalogs only'
complete -c reindexdb -s S -d 'Reindex schema only'
complete -c reindexdb -s t -d 'Reindex table only'
complete -c reindexdb -l tablespace -d 'Specifies the tablespace where indexes are rebuilt'
complete -c reindexdb -o 'v
.br
--verbose' -d 'Print detailed information during processing'
complete -c reindexdb -o 'V
.br
--version' -d 'Print the reindexdb version and exit'
complete -c reindexdb -o '?
.br
--help' -d 'Show help about reindexdb command line arguments, and exit'
complete -c reindexdb -s h -d 'Specifies the host name of the machine on which the server is running'
complete -c reindexdb -s p -d 'Specifies the TCP port or local Unix domain socket file extension on which th…'
complete -c reindexdb -s U -d 'User name to connect as'
complete -c reindexdb -o 'w
.br
--no-password' -d 'Never issue a password prompt'
complete -c reindexdb -o 'W
.br
--password' -d 'Force reindexdb to prompt for a password before connecting to a database'
complete -c reindexdb -l maintenance-db -d 'Specifies the name of the database to connect to to discover which databases …'
complete -c reindexdb -s a
complete -c reindexdb -l all
complete -c reindexdb -o a/--all -d 'is not used'
complete -c reindexdb -s e
complete -c reindexdb -l echo
complete -c reindexdb -l index
complete -c reindexdb -l jobs
complete -c reindexdb -l system -d options
complete -c reindexdb -s q
complete -c reindexdb -l quiet
complete -c reindexdb -s s
complete -c reindexdb -l schema
complete -c reindexdb -l table
complete -c reindexdb -s v
complete -c reindexdb -l verbose
complete -c reindexdb -s V
complete -c reindexdb -l version
complete -c reindexdb -s '?'
complete -c reindexdb -l help
complete -c reindexdb -l host
complete -c reindexdb -l port
complete -c reindexdb -l username
complete -c reindexdb -s w
complete -c reindexdb -l no-password
complete -c reindexdb -s W
complete -c reindexdb -l password

