# rlogind
# Autogenerated from man page /usr/share/man/man8/rlogind.8.gz
complete -c rlogind -s 4 -l ipv4 -d 'daemon mode only accepts IPv4'
complete -c rlogind -s 6 -l ipv6 -d 'only IPv6 in daemon mode'
complete -c rlogind -s a -l verify-hostname -d 'ask hostname for verification'
complete -c rlogind -s d -l daemon -d 'daemon mode, with instance limit'
complete -c rlogind -s D -l debug -d 'set debug level'
complete -c rlogind -s l -l no-rhosts -d 'ignore . rhosts file'
complete -c rlogind -s L -l local-domain -d 'set local domain name'
complete -c rlogind -s n -l no-keepalive -d 'do not set SO_KEEPALIVE'
complete -c rlogind -s o -l allow-root -d 'allow uid 0 to login, disabled by default'
complete -c rlogind -s p -l port -d 'listen on given port (valid only in daemon mode)'
complete -c rlogind -s r -l reverse-required -d 'require reverse resolving of a remote host IP'
complete -c rlogind -s '?' -l help -d 'give this help list'
complete -c rlogind -l usage -d 'give a short usage message'
complete -c rlogind -s V -l version -d 'print program version'

