# rlogin
# Autogenerated from man page /usr/share/man/man1/rlogin.1.gz
complete -c rlogin -s 4 -l ipv4 -d 'use only IPv4'
complete -c rlogin -s 6 -l ipv6 -d 'use only IPv6'
complete -c rlogin -s 8 -l 8-bit -d 'allows an eight-bit input data path at all times'
complete -c rlogin -s d -l debug -d 'set the SO_DEBUG option'
complete -c rlogin -s e -l escape -d 'allows user specification of the escape character, which is ``~\'\' by default'
complete -c rlogin -s E -l no-escape -d 'stops any character from being recognized as an escape character'
complete -c rlogin -s l -l user -d 'run as USER on the remote system'
complete -c rlogin -s '?' -l help -d 'give this help list'
complete -c rlogin -l usage -d 'give a short usage message'
complete -c rlogin -s V -l version -d 'print program version'

