# rmiregistry-openjdk17
# Autogenerated from man page /usr/share/man/man1/rmiregistry-openjdk17.1.gz
complete -c rmiregistry-openjdk17 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-openjdk17 -s J -s J -d 'Java interpreter'

