# rmiregistry-openjdk20
# Autogenerated from man page /usr/share/man/man1/rmiregistry-openjdk20.1.gz
complete -c rmiregistry-openjdk20 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-openjdk20 -s J -s J -d 'Java interpreter'

