# rsh
# Autogenerated from man page /usr/share/man/man1/rsh.1.gz
complete -c rsh -s 4 -l ipv4 -d 'use only IPv4'
complete -c rsh -s 6 -l ipv6 -d 'use only IPv6'
complete -c rsh -s 8 -l 8-bit -d 'allows an eight-bit input data path at all times'
complete -c rsh -s d -l debug -d 'turns on socket debugging (see setsockopt(2))'
complete -c rsh -s e -l escape -d 'allows user specification of the escape character (``~\'\' by default)'
complete -c rsh -s l -l user -d 'run as USER on the remote system'
complete -c rsh -s n -l no-input -d 'use \\,/dev/null\\/ as input'
complete -c rsh -s '?' -l help -d 'give this help list'
complete -c rsh -l usage -d 'give a short usage message'
complete -c rsh -s V -l version -d 'print program version'

