# rshd
# Autogenerated from man page /usr/share/man/man8/rshd.8.gz
complete -c rshd -s a -l verify-hostname -d 'ask hostname for verification'
complete -c rshd -s l -l no-rhosts -d 'ignore . rhosts file'
complete -c rshd -s L -l log-sessions -d 'log successful logins'
complete -c rshd -s n -l no-keepalive -d 'do not set SO_KEEPALIVE'
complete -c rshd -s r -l reverse-required -d 'require reverse resolving of remote host IP'
complete -c rshd -s '?' -l help -d 'give this help list'
complete -c rshd -l usage -d 'give a short usage message'
complete -c rshd -s V -l version -d 'print program version AUTHOR Written by many authors'

