# serdi
# Autogenerated from man page /usr/share/man/man1/serdi.1.gz
complete -c serdi -s a -d 'Write ASCII output'
complete -c serdi -s b -d 'Bulk output writing'
complete -c serdi -s c -d 'Chop prefix from matching blank node IDs.  This is the inverse of p.  Pp'
complete -c serdi -s e -d 'Eat input one character at a time, rather than a page at a time which is the …'
complete -c serdi -s f -d 'Keep full URIs in input (don\'t qualify with namespace prefixes or make URIs r…'
complete -c serdi -s h -d 'Print the command line options.  Pp'
complete -c serdi -s i -d 'Read input as syntax'
complete -c serdi -s l -d 'Lax (non-strict) parsing'
complete -c serdi -s o -d 'Write output as syntax'
complete -c serdi -s p -d 'Add prefix to blank node IDs'
complete -c serdi -s q -d 'Suppress all output except data.  Pp'
complete -c serdi -s r -d 'Keep relative URIs within a root URI'
complete -c serdi -s s -d 'Parse string input instead of a file (terminates options).  Pp'
complete -c serdi -s v -d 'Display version information and exit'

