# smbios-battery-ctl
# Autogenerated from man page /usr/share/man/man1/smbios-battery-ctl.1.gz
complete -c smbios-battery-ctl -l version -d 'show program\'s version number and exit'
complete -c smbios-battery-ctl -s h -l help -d 'show this help message and exit'
complete -c smbios-battery-ctl -s v -l verbose -d 'Display more verbose output'
complete -c smbios-battery-ctl -s q -l quiet -d 'Minimize program output.  Only errors and warnings are displayed'
complete -c smbios-battery-ctl -l trace -d 'Enable verbose function tracing'
complete -c smbios-battery-ctl -l logconfig -d 'Specify alternate config log'
complete -c smbios-battery-ctl -l security-key -d 'BIOS pre-calculated security key'
complete -c smbios-battery-ctl -l password -d 'BIOS Setup password for set/activate operations'
complete -c smbios-battery-ctl -s r -l rawpassword -d 'Do not auto-convert password to scancodes'
complete -c smbios-battery-ctl -l memory-dat -d 'Path to a memory dump file to use instead of real RAM'
complete -c smbios-battery-ctl -l cmos-dat -d 'Path to a CMOS dump file to use instead of real CMOS'
complete -c smbios-battery-ctl -s c -l battery-charge -d 'This will get the Current Battery Charging State'
complete -c smbios-battery-ctl -l get-charging-cfg -d 'Get the current Primary Battery Charge Configuration'
complete -c smbios-battery-ctl -l set-charging-mode -d 'Set the current Primary Battery Charge Configuration'
complete -c smbios-battery-ctl -l set-custom-charge-interval -d 'Set the percentage bounds for custom charge.  Both must be integers'

