# smbios-wakeup-ctl
# Autogenerated from man page /usr/share/man/man1/smbios-wakeup-ctl.1.gz
complete -c smbios-wakeup-ctl -l version -d 'show program\'s version number and exit'
complete -c smbios-wakeup-ctl -s h -l help -d 'show this help message and exit'
complete -c smbios-wakeup-ctl -l hour -d 'Set wakeup hour.  Must be 0-23'
complete -c smbios-wakeup-ctl -l minute -d 'Set wakeup minute.  Must be 0-59'
complete -c smbios-wakeup-ctl -l everyday -d 'Set wakeup for every day'
complete -c smbios-wakeup-ctl -l weekday -d 'Set wakeup for weekdays only'
complete -c smbios-wakeup-ctl -l disable -d 'Disable wakeups'
complete -c smbios-wakeup-ctl -s v -l verbose -d 'Display more verbose output'
complete -c smbios-wakeup-ctl -s q -l quiet -d 'Minimize program output.  Only errors and warnings are displayed'
complete -c smbios-wakeup-ctl -l trace -d 'Enable verbose function tracing'
complete -c smbios-wakeup-ctl -l logconfig -d 'Specify alternate config log'
complete -c smbios-wakeup-ctl -l password -d 'BIOS Setup password for set/activate operations'
complete -c smbios-wakeup-ctl -s r -l rawpassword -d 'Do not auto-convert password to scancodes'
complete -c smbios-wakeup-ctl -l memory-dat -d 'Path to a memory dump file to use instead of real RAM'
complete -c smbios-wakeup-ctl -l cmos-dat -d 'Path to a CMOS dump file to use instead of real CMOS SEE ALSO The full docume…'

