# smbios-lcd-brightness
# Autogenerated from man page /usr/share/man/man1/smbios-lcd-brightness.1.gz
complete -c smbios-lcd-brightness -l version -d 'show program\'s version number and exit'
complete -c smbios-lcd-brightness -s h -l help -d 'show this help message and exit'
complete -c smbios-lcd-brightness -s v -l verbose -d 'Display more verbose output'
complete -c smbios-lcd-brightness -s q -l quiet -d 'Minimize program output.  Only errors and warnings are displayed'
complete -c smbios-lcd-brightness -l trace -d 'Enable verbose function tracing'
complete -c smbios-lcd-brightness -l logconfig -d 'Specify alternate config log'
complete -c smbios-lcd-brightness -l security-key -d 'BIOS pre-calculated security key'
complete -c smbios-lcd-brightness -l password -d 'BIOS Setup password for set/activate operations'
complete -c smbios-lcd-brightness -s r -l rawpassword -d 'Do not auto-convert password to scancodes'
complete -c smbios-lcd-brightness -l memory-dat -d 'Path to a memory dump file to use instead of real RAM'
complete -c smbios-lcd-brightness -l cmos-dat -d 'Path to a CMOS dump file to use instead of real CMOS'
complete -c smbios-lcd-brightness -l value -d 'Set new value'
complete -c smbios-lcd-brightness -s b -l battery -d 'Set new value to be used while running on battery power'
complete -c smbios-lcd-brightness -s a -l ac -d 'Set new value to be used while running on AC power SEE ALSO The full document…'

