# smbios-thermal-ctl
# Autogenerated from man page /usr/share/man/man1/smbios-thermal-ctl.1.gz
complete -c smbios-thermal-ctl -l version -d 'show program\'s version number and exit'
complete -c smbios-thermal-ctl -s h -l help -d 'show this help message and exit'
complete -c smbios-thermal-ctl -s i -l info -d 'This will Display the Supported Features of USTT and AAC'
complete -c smbios-thermal-ctl -s g -l get-thermal-info -d 'This will Display the Thermal Information of a system'
complete -c smbios-thermal-ctl -l set-thermal-mode -d 'Option to set Thermal Mode; balanced, cool-bottom, quiet, performance'
complete -c smbios-thermal-ctl -s v -l verbose -d 'Display more verbose output'
complete -c smbios-thermal-ctl -s q -l quiet -d 'Minimize program output.  Only errors and warnings are displayed'
complete -c smbios-thermal-ctl -l trace -d 'Enable verbose function tracing'
complete -c smbios-thermal-ctl -l logconfig -d 'Specify alternate config log'
complete -c smbios-thermal-ctl -l security-key -d 'BIOS pre-calculated security key'
complete -c smbios-thermal-ctl -l password -d 'BIOS Setup password for set/activate operations'
complete -c smbios-thermal-ctl -s r -l rawpassword -d 'Do not auto-convert password to scancodes'
complete -c smbios-thermal-ctl -l memory-dat -d 'Path to a memory dump file to use instead of real RAM'
complete -c smbios-thermal-ctl -l cmos-dat -d 'Path to a CMOS dump file to use instead of real CMOS SEE ALSO The full docume…'

