# smbios-sys-info
# Autogenerated from man page /usr/share/man/man1/smbios-sys-info.1.gz
complete -c smbios-sys-info -l version -d 'show program\'s version number and exit'
complete -c smbios-sys-info -s h -l help -d 'show this help message and exit'
complete -c smbios-sys-info -l service-tag -d 'Show or set service tag'
complete -c smbios-sys-info -l asset-tag -d 'Show or set asset tag'
complete -c smbios-sys-info -l property-tag -d 'Show or set property tag'
complete -c smbios-sys-info -l set -d 'Set specified tag to new value'
complete -c smbios-sys-info -s v -l verbose -d 'Display more verbose output'
complete -c smbios-sys-info -s q -l quiet -d 'Minimize program output.  Only errors and warnings are displayed'
complete -c smbios-sys-info -l trace -d 'Enable verbose function tracing'
complete -c smbios-sys-info -l logconfig -d 'Specify alternate config log'
complete -c smbios-sys-info -l password -d 'BIOS Setup password for set/activate operations'
complete -c smbios-sys-info -s r -l rawpassword -d 'Do not auto-convert password to scancodes'
complete -c smbios-sys-info -l memory-dat -d 'Path to a memory dump file to use instead of real RAM'
complete -c smbios-sys-info -l cmos-dat -d 'Path to a CMOS dump file to use instead of real CMOS SEE ALSO The full docume…'

