# smbios-passwd
# Autogenerated from man page /usr/share/man/man1/smbios-passwd.1.gz
complete -c smbios-passwd -l version -d 'show program\'s version number and exit'
complete -c smbios-passwd -s h -l help -d 'show this help message and exit'
complete -c smbios-passwd -l info -d 'Show password information'
complete -c smbios-passwd -s v -l verbose -d 'Display more verbose output'
complete -c smbios-passwd -s q -l quiet -d 'Minimize program output.  Only errors and warnings are displayed'
complete -c smbios-passwd -l trace -d 'Enable verbose function tracing'
complete -c smbios-passwd -l logconfig -d 'Specify alternate config log'
complete -c smbios-passwd -l password -d 'BIOS Setup password for set/activate operations'
complete -c smbios-passwd -s r -l rawpassword -d 'Do not auto-convert password to scancodes'
complete -c smbios-passwd -l memory-dat -d 'Path to a memory dump file to use instead of real RAM'
complete -c smbios-passwd -l cmos-dat -d 'Path to a CMOS dump file to use instead of real CMOS SEE ALSO The full docume…'

