# smbios-get-ut-data
# Autogenerated from man page /usr/share/man/man1/smbios-get-ut-data.1.gz
complete -c smbios-get-ut-data -l help -s h -d 'Displays this information'
complete -c smbios-get-ut-data -l cmos_file -s c -d 'Debug: CMOS dump file to use instead of physical cmos'
complete -c smbios-get-ut-data -l memory_file -s m -d 'Debug: Memory dump file to use instead of physical memory'
complete -c smbios-get-ut-data -l version -s v -d 'Display libsmbios version information SEE ALSO The full documentation for smb…'

