# smbios-upflag-ctl
# Autogenerated from man page /usr/share/man/man1/smbios-upflag-ctl.1.gz
complete -c smbios-upflag-ctl -l help -s h -d 'Displays this information'
complete -c smbios-upflag-ctl -l memory_file -s m -d 'Debug: Memory dump file to use instead of physical memory'
complete -c smbios-upflag-ctl -l cmos_file -s c -d 'Debug: CMOS dump file to use instead of physical cmos'
complete -c smbios-upflag-ctl -l set -s s -d 'Set Boot To UP Flag to true'
complete -c smbios-upflag-ctl -l clear -d 'Set Boot To UP Flag to false'
complete -c smbios-upflag-ctl -l get -s g -d 'Set Boot To UP Flag to true'
complete -c smbios-upflag-ctl -l version -s v -d 'Display libsmbios version information SEE ALSO The full documentation for smb…'

