# smbios-sys-info-lite
# Autogenerated from man page /usr/share/man/man1/smbios-sys-info-lite.1.gz
complete -c smbios-sys-info-lite -l help -s h -d 'Displays this information'
complete -c smbios-sys-info-lite -l memory_file -s m -d 'Debug: Memory dump file to use instead of physical memory'
complete -c smbios-sys-info-lite -l version -s v -d 'Display libsmbios version information SEE ALSO The full documentation for smb…'

