# smbios-state-byte-ctl
# Autogenerated from man page /usr/share/man/man1/smbios-state-byte-ctl.1.gz
complete -c smbios-state-byte-ctl -l help -s h -d 'Displays this information'
complete -c smbios-state-byte-ctl -l memory_file -s m -d 'Debug: Memory dump file to use instead of physical memory'
complete -c smbios-state-byte-ctl -l cmos_file -s c -d 'Debug: CMOS dump file to use instead of physical cmos'
complete -c smbios-state-byte-ctl -l set -s s -d 'Set CMOS state byte to new value'
complete -c smbios-state-byte-ctl -l owner -s o -d 'Set state byte owner'
complete -c smbios-state-byte-ctl -l version -s v -d 'Display libsmbios version information SEE ALSO The full documentation for smb…'

