# swayidle
# Autogenerated from man page /usr/share/man/man1/swayidle.1.gz
complete -c swayidle -s C -d 'The config file to use'
complete -c swayidle -s h -d 'Show help message and quit'
complete -c swayidle -s d -d 'Enable debug output'
complete -c swayidle -s w -d 'Wait for command to finish executing before continuing, helpful for ensuring'
complete -c swayidle -s S -d 'Specify which seat to use'

