# swaymsg
# Autogenerated from man page /usr/share/man/man1/swaymsg.1.gz
complete -c swaymsg -s h -l help -d 'Show help message and quit'
complete -c swaymsg -s m -l monitor -d 'Monitor for responses until killed instead of exiting after the first'
complete -c swaymsg -s p -l pretty -d 'Use pretty output even when not using a tty'
complete -c swaymsg -s q -l quiet -d 'Sends the IPC message but does not print the response from sway'
complete -c swaymsg -s r -l raw -d 'Use raw JSON output even if using a tty'
complete -c swaymsg -s s -l socket -d 'Use the specified socket path.  Otherwise, swaymsg will ask sway where the'
complete -c swaymsg -s t -l type -d 'Specify the type of IPC message.  See below'
complete -c swaymsg -s v -l version -d 'Print the version (of swaymsg) and quit'

