# sway
# Autogenerated from man page /usr/share/man/man1/sway.1.gz
complete -c sway -s h -l help -d 'Show help message and quit'
complete -c sway -s c -l config -d 'Specifies a config file'
complete -c sway -s C -l validate -d 'Check the validity of the config file, then exit'
complete -c sway -s d -l debug -d 'Enables full logging, including debug information'
complete -c sway -s v -l version -d 'Show the version number and quit'
complete -c sway -s V -l verbose -d 'Enables more verbose logging'
complete -c sway -l get-socketpath -d 'Gets the IPC socket path and prints it, then exits'

