# swaybg
# Autogenerated from man page /usr/share/man/man1/swaybg.1.gz
complete -c swaybg -s c -l color -d 'Set the background color'
complete -c swaybg -s h -l help -d 'Show help message and quit'
complete -c swaybg -s i -l image -d 'Set the background image'
complete -c swaybg -s m -l mode -d 'Scaling mode for images: stretch, fill, fit, center, or tile.  Use'
complete -c swaybg -s o -l output -d 'Select an output to configure.  Subsequent appearance options will only'
complete -c swaybg -s v -l version -d 'Show the version number and quit'

