# talk
# Autogenerated from man page /usr/share/man/man1/talk.1.gz
complete -c talk -s '?' -l help -d 'give this help list'
complete -c talk -l usage -d 'give a short usage message'
complete -c talk -s V -l version -d 'print program version AUTHOR Written by Kipp Hickman, Clem Cole, and Peter Mo…'

