# talkd
# Autogenerated from man page /usr/share/man/man8/talkd.8.gz
complete -c talkd -s a -l acl -d 'read site-wide ACLs from FILE'
complete -c talkd -s d -l debug -d 'enable debugging '
complete -c talkd -s l -l logging -d 'enable more syslog reporting'
complete -c talkd -s r -l request-ttl -d 'set request time-to-live value to SECONDS'
complete -c talkd -s S -l strict-policy -d 'apply strict ACL policy'
complete -c talkd -s t -l timeout -d 'set timeout value to SECONDS'
complete -c talkd -s '?' -l help -d 'give this help list'
complete -c talkd -l usage -d 'give a short usage message'
complete -c talkd -s i -l idle-timeout
complete -c talkd -s V -l version -d 'print program version'

