# wesside-ng
# Autogenerated from man page /usr/share/man/man8/wesside-ng.8.gz
complete -c wesside-ng -s h -d 'Shows the help screen'
complete -c wesside-ng -s i -d 'Wireless interface name.  (Mandatory)'
complete -c wesside-ng -s n -d 'Network IP as in \\(aqwho has destination IP (netip) tell source IP (myip)\\(aq'
complete -c wesside-ng -s m -d '\\(aqwho has destination IP (netip) tell source IP (myip)\\(aq'
complete -c wesside-ng -s a -d 'Source MAC address (Optional)'
complete -c wesside-ng -s c -d 'Do not crack the key'
complete -c wesside-ng -s p -d 'Determines the minimum number of bytes of PRGA which is gathered'
complete -c wesside-ng -s v -d 'Wireless access point MAC address (Optional)'
complete -c wesside-ng -s t -d 'For each number of IVs specified, restart the airecrack-ng PTW engine (Option…'
complete -c wesside-ng -s f -d 'Allows the highest channel for scanning to be defined'

