# wl-clipboard
# Autogenerated from man page /usr/share/man/man1/wl-clipboard.1.gz
complete -c wl-clipboard -s p -l primary -d 'Use the "primary" clipboard instead of the regular clipboard'
complete -c wl-clipboard -s o -l paste-once -d 'Only serve one paste request and then exit'
complete -c wl-clipboard -s f -l foreground -d 'By default, wl-copy forks and serves data requests in the background; this op…'
complete -c wl-clipboard -s c -l clear -d 'Instead of copying anything, clear the clipboard so that nothing is copied'
complete -c wl-clipboard -s n -l trim-newline -d 'Do not copy the trailing newline character if it is present in the input file'
complete -c wl-clipboard -l no-newline -d 'Do not append a newline character after the pasted clipboard content'
complete -c wl-clipboard -s t -l type -d 'Override the automatically selected MIME type'
complete -c wl-clipboard -s s -l seat -d 'Specify which seat wl-copy and wl-paste should work with'
complete -c wl-clipboard -s l -l list-types -d 'Instead of pasting the selection, output the list of MIME types it is offered…'
complete -c wl-clipboard -s w -l watch -d 'Instead of pasting once and exiting, continuously watch the clipboard for cha…'
complete -c wl-clipboard -s v -l version -d 'Display the version of wl-clipboard and some short info about its license'
complete -c wl-clipboard -s h -l help -d 'Display a short help message listing the available options.  ENVIRONMENT'

