# zipcmp
# Autogenerated from man page /usr/share/man/man1/zipcmp.1.gz
complete -c zipcmp -s C -d 'Check consistency of archives'
complete -c zipcmp -s h -d 'Display a short help message and exit'
complete -c zipcmp -s i -d 'Compare names ignoring case distinctions'
complete -c zipcmp -s p -d 'Enable paranoid checks.  Compares extra fields, comments, and other meta data'
complete -c zipcmp -s q -d 'Quiet mode.  Compare v'
complete -c zipcmp -s s -d 'Print a summary of how many files where added and removed'
complete -c zipcmp -s t -d 'Test zip files by comparing the contents to their checksums'
complete -c zipcmp -s V -d 'Display version information and exit'
complete -c zipcmp -s v -d 'Verbose mode.  Print details about differences to stdout'

