# ziptool
# Autogenerated from man page /usr/share/man/man1/ziptool.1.gz
complete -c ziptool -s c -d 'Check zip archive consistency when opening it'
complete -c ziptool -s e -d 'Error if archive already exists (only useful with n )'
complete -c ziptool -s g -d 'Guess file name encoding (for stat command)'
complete -c ziptool -s h -d 'Display help'
complete -c ziptool -s l -d 'Only read length bytes of archive.  See also o'
complete -c ziptool -s n -d 'Create archive if it doesn\'t exist.  See also e'
complete -c ziptool -s o -d 'Start reading input archive from offset.  See also l'
complete -c ziptool -s r -d 'Print raw file name encoding without translation (for stat command)'
complete -c ziptool -s s -d 'Follow file name convention strictly (for stat command)'
complete -c ziptool -s t -d 'Disregard current file contents, if any'

